### ISSUE TITLE
tracker-current-pattern is an undefined function

### ISSUE THREAD

**Issue by steve-blobs** [defaultxr/tracker-mode#1]
Hi, awesome program. After freshly git cloning and evaluating the code, I received the error from the title and confirmed it myself. I spent a couple hours trying to fix it but I'm not good with emacs lisp (I started having issues with search-forward-regexp and search-backward-regexp within the tracker-goto-step function).

Anyhow if you get time to update the code with tracker-current-pattern and perhaps confirm that a fresh git clone works on a vanilla `emacs -q` I'd really appreciate it.

**Comment by defaultxr** [comment]
Strange, even in my local copy I'm not seeing that function. I'll have a look and see if I can reimplement and make sure it's working properly.

**Comment by steve-blobs** [comment]
Hey thanks for getting back to me! I had simply cloned the repo, so my copy is identical to this:
https://github.com/defaultxr/tracker-mode/blob/master/tracker.el

By cntrl-f'ing for 'tracker-current-pattern' you should see it.

**Comment by defaultxr** [comment]
True, I was definitely seeing references to the function, just not a copy of the function definition itself.

I looked through the history and was able to find a copy of the function in a previous commit, but even with it, the tracker is still in a pretty broken/unusable state right now. I think I was in the middle of making some big updates to it before and left it like that. I didn't think the repo copy was also broken though. Anyway, I've been working on updating and fixing it but it might be a bit before that's completed. Hopefully within a couple days but no guarantees on a real timeframe.

**Comment by defaultxr** [comment]
OK, I updated this and it should be working again now. There are a few bugs but I think the basic functionality works as expected. It definitely still needs some work and more cleaning up in the future, especially since there are still parts of the code left over from when I first started it years ago, back when I was still new to Lisp and Emacs in general.

Let me know if you have any questions or any issues with it. Happy hacking :^)
