### ISSUE TITLE
cl-lib errors

### ISSUE THREAD

**Issue by ctsUX** [defaultxr/tracker-mode#3]
Hey man, after running "tracker" it was throwing errors for "getf" and "list*", which it turns out have become "cl-getf" and "cl-list*" in cl-lib. I changed em and now it works. With (require 'cl) getf and list* work, but with cl-lib the cl- prefixes are necessary. I sent a PR with the edits.

Anyways, just want to tell you that I was daydreaming earlier about an Emacs tracker and decided to see if anyone else has had the same idea, though I wasn't expecting anything... And lo and behold! Amazing! 😄 I'm about to play with it now! Thanks a lot! 😃

**Comment by defaultxr** [comment]
No prob, and thank you for the patch! :) To be honest tracker-mode is nothing special right now, but I do intend to continue developing it in the future (I have a bunch of the ideas listed in the "Future" section of the readme).

I actually have a work-in-progress version of a tabulated-list-mode-based sequencer in my local copy of this repo; if that ends up being an idea worth following I'll publish it as part of this library in the future. Since there is interest I may try to spend some more time on tracker-mode again soon.

Anyway, thanks for the kind words, and hope you're able to get some enjoyment out of it :)

**Comment by ngeiswei** [comment]
@cts-ux, if you get a chance to stream yourself while using tracker-mode please let us know!  I've personally been interested in trying it for a while.

**Comment by ctsUX** [comment]
@defaultxr: If I can edit sequences in Emacs and they play in Renoise then it's already very special imo. 😄 I hope to contribute to this project in whatever meaningful ways I can in the future. I'll check out your ideas list and see what catches my attention and seems feasible for me. I also need to try out piano-mode! And the tabulated-list-mode version sounds awesome! Tracking in Emacs sounds like a dream, so I definitely think all of this is worth pursuing. The human-computer interaction obstacle is a real killer when it comes to musical creativity, for me at least. I'm also gonna try making a Renoise QMK layer with VIM-style navigation. That could also be nice. We'll see! Anyways, thanks again! 😃

**Comment by ctsUX** [comment]
@ngeiswei: I'm not a streamer, but maybe I could manage a video at some point. We'll see! I'll let you know if I do!
